sudo: false
language: node_js
cache:
  directories:
    - node_modules
node_js:
  - "0.11"
env:
  # express 3.0 was released late 2012
  # gm 1.2.0 added extent and gravity
  # mime 1.1.0 added extension
  - MODULES="express@~3 gm@1.2.0 mime@1.1.0"
  - MODULES=""
install:
  - npm install $MODULES
  - npm install
after_script:
  # @see https://github.com/cainus/node-coveralls#istanbul
  - DELAY=100 WHITELIST=localhost istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
